doc/team.txt

Add Armi as a team member

---

doc/team.txt

added my name to the text file

---

doc/team.txt

Hello Team,
Adding my CCID and GitHub username for the project part 1 requirements. Can someone please review and approve this :) ?

add Taranjot's ccid and username to team doc file

---

doc/p1-uml.txt

Super duper simple UML for Profile. Looking for commentary on how in depth I should go and also if I'm following the pattern correctly.

Add UML for profile

---

doc/p1-uml.txt

- Added UML diagram for Library path 
**Things I'm unsure about**
- Use of correct terminology re the camera, google maps, and handoff service. I thought of them as placeholders to access the API's to use the camera, google maps, and to notify the to initiate handoff sequence
- Having individual VM's for profile and book views, they would get their data from the activity level VM, and would house logic to update Profile and Book models. Also have logic for Handoff, Accepting/Declining requests, and google maps location setting

Added Library UML diagram

---

doc/p1-uml.txt

Hello Friends,
Please see this UML diagram and provide any thoughts.
In particular, these are things to note/discuss:
1) After removing the ViewModels for the Fragments, all the methods that handle the logic for what happens when a button on the fragment is clicked are now in the parent activity's ViewModel class. We will have to "propogate" the button clicks back to the parent activity so we can access the methods of the parent's ViewModel but that should not be too hard and the methods for that seem irrelevant to include here.
2) I don't quite understand why we need the aggregation between the ProfileFragment class and the ProfileActivity class. I get that they are similar so shouldn't we just keep one or the other? Like just keep the ProfileActivity and have the BookFragement directly …

modify the UML diagram according to our discussion today

---

app/build.gradle
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
app/src/main/java/com/example/unlibrary/models/Book.java
app/src/main/java/com/example/unlibrary/models/Request.java
app/src/main/java/com/example/unlibrary/models/User.java

- Empty constructors are needed for Firestore
- Every attribute needs a getter for Firestore
- Add Book, User, Request entities as specified in #19 
- Timestamps suggested were not added to simplify this PR a bit (also it wasn't in our UI mockups)
- _`DECLINED`_ state has been merged with _`ARCHIVED`_
- Link with repository
- Verify that Pair<Double, Double> lat lon can be stored in Firestore
- Add basic rules in Firestore so that only authenticated users can read data and users can only modify their own user information
- Link Firebase ID with mId in User class
- Check if we can add a reference type in Firestore in custom objects (User, Request, Book)
- Add tests with Firebase

Add basic entity classes

---

app/build.gradle
app/src/androidTest/java/com/example/unlibrary/ExampleInstrumentedTest.java
app/src/main/java/com/example/unlibrary/auth/AuthActivity.java
app/src/main/java/com/example/unlibrary/auth/AuthRepository.java
app/src/main/java/com/example/unlibrary/auth/AuthViewModel.java
app/src/main/java/com/example/unlibrary/auth/LoginFragment.java
app/src/main/java/com/example/unlibrary/auth/RegisterFragment.java
app/src/main/java/com/example/unlibrary/models/User.java
app/src/main/java/com/example/unlibrary/util/AuthenticatedActivity.java
app/src/main/java/com/example/unlibrary/util/SingleLiveEvent.java
app/src/main/res/layout/fragment_login.xml
app/src/test/java/com/example/unlibrary/auth/AuthViewModelTest.java
app/src/test/java/com/example/unlibrary/helper/LiveDataTestUtil.java

- Move firebase code to repository
- Remove unnecessary fields from user model
- Move some errors to be inline on the text fields
- Comment out tests until @armiantos figures out mocking
- Add validation to input values
- Generate a user document when registering a user
- @armiantos I made some changes to the User model
- Once this merges we should delete everyone from firebase auth and make them sign up again.

Improve authentication

---

app/src/main/res/layout/activity_main.xml

MainFragment contents no longer go behind the bottom nav bar

Fix NavHostFragment constraints

---

app/src/main/java/com/example/unlibrary/exchange/ExchangeBookRecyclerViewAdapter.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeBooksFragment.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeViewModel.java
app/src/main/java/com/example/unlibrary/models/Book.java
app/src/main/res/drawable/ic_add.xml
app/src/main/res/drawable/ic_baseline_search_24.xml
app/src/main/res/drawable/ic_search.xml
app/src/main/res/drawable/search_input.xml
app/src/main/res/drawable/status_color.xml
app/src/main/res/layout/fragment_exchange.xml
app/src/main/res/layout/fragment_library.xml
app/src/main/res/layout/fragment_library_book.xml
app/src/main/res/layout/fragment_library_book_list.xml
app/src/main/res/values/colors.xml
app/src/main/res/values/strings.xml
app/src/main/res/values/styles.xml

- Created the exchange fragment to show the list of requested and available books
- TODO: need to find out how to get the id of the logged in user and the book owner to customize the view for each fragment
- TODO: need to know how to store the images taken by the camera to retrieve in the view
- Made the first version of library layout to show all books and two floating buttons for filtering and adding books

Taran golnoush/exchange fragment improved

---

app/src/main/java/com/example/unlibrary/library/FilterMap.java
app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
app/src/main/java/com/example/unlibrary/util/AuthenticatedActivity.java
app/src/main/res/layout/fragment_library.xml
app/src/main/res/values/strings.xml

- Add filter functionality to Library book list
- Update delete dialog to use material view dialog
Doesn't directly close any tickets that I'm aware of.

Filter library book list

---

app/src/main/java/com/example/unlibrary/models/Request.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java

- Add setters for mRequester and mBook in Requests.java class
- Add query so only books that are associated to a request made by this user show up in the list
- Change query later depending on new data model for firestore
-  use getDocumentChanges instead to minimize payload from Firestore
- add functionality in app to allow users to remove Achieved requests once seen
Closes 69

Update UnlibraryRepository query

---

app/src/main/java/com/example/unlibrary/book_detail/BookDetailFragment.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeBookDetailsFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryBookDetailsFragment.java
app/src/main/res/layout/fragment_exchange_book_details.xml
app/src/main/res/layout/fragment_library_book_details.xml
app/src/main/res/layout/fragment_unlibrary_book_details.xml

- enlarge book's photo on click
- shrink photo by tapping anywhere on the screen
- referenced [this](https://developer.android.com/training/animation/zoom) resource and I cited it in the source code
(apologies for the obnoxiously large gif lol idk how to resize it)
Closes #94

Enlarge Book's Photo on Click

---

app/src/main/java/com/example/unlibrary/models/Request.java
build.gradle

- updates requests to use geopoint for location

updated to geopoint

---

app/src/main/java/com/example/unlibrary/exchange/ExchangeFragment.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeViewModel.java
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
app/src/main/res/layout/fragment_exchange_book_details.xml
app/src/main/res/layout/fragment_library_book_details.xml

- Prevent creating duplicate requests for a book
- Update a book to `REQUESTED` when requesting a book in exchange
closes #81 
closes #99

Update book status when requesting a book in exchange

---

app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryBookDetailsFragment.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryViewModel.java
app/src/main/res/layout/fragment_exchange_book_details.xml
app/src/main/res/layout/fragment_unlibrary_book_details.xml
app/src/main/res/values/strings.xml

- Shows the owner of the book on Unlibrary detailed bookview
- Removed profile icon from Exchange and Unlibrary detailed bookviews

Show unlibrary book owner

---

app/src/main/java/com/example/unlibrary/auth/AuthActivity.java
app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryViewModel.java
app/src/main/java/com/example/unlibrary/util/BarcodeScanner.java
app/src/main/java/com/example/unlibrary/util/FilterMap.java

- Prevent deleting books that have active requests
- Random formatting

Fix Unlibrary crash

---

app/src/main/java/com/example/unlibrary/library/LibraryEditBookFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
app/src/main/res/layout/fragment_library_edit_book.xml

- Added a fab for deleting a book's photo on Library Edit Book
- The owner can remove the current photo of their books

delete book image

---

app/src/main/res/layout/fragment_library_requester_profile.xml

- Hide the accept and cancel button in the Library Requester Profile page
Closes #125

hide buttons in requester profile if the request is accepted

---

app/src/main/java/com/example/unlibrary/library/LibraryMapsFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryBookDetailsFragment.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryMapsFragment.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryViewModel.java
app/src/main/res/layout/fragment_maps.xml
app/src/main/res/layout/fragment_unlibrary_book_details.xml
app/src/main/res/navigation/nav_graph.xml
app/src/main/res/values/strings.xml

- Show handoff location in unlibrary detail book view 
- Clicking the map preview will navigate to a full page map fragment but no autocomplete search bar 
- Small refactor to map fragment in library (renamed it and updated navigation)
- If you're working on UI

Show handoff location in unlibrary

---

app/src/main/res/layout/fragment_login.xml

Make email a single line input

---

app/src/main/java/com/example/unlibrary/util/FilterMap.java

- Changed which option is displayed to properly filter

Fix unlibrary filter

---

app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java

Was trying to test the app end to end and I kept encountering null pointer exceptions. They're mostly cases of when a LiveData value gets set to null and we don't handle that case somewhere.

Handle multiple places where null pointer exceptions occur

---

build.gradle
gradle/wrapper/gradle-wrapper.properties

- List of features this PR will add
- If you're working on UI
- List of tasks that is too big for this PR and will be done in future PRs or some known issues to fix
- Don't forget to create new tasks to monitor these
Closes insert-issue-number-here

Revert gradle

---

app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryViewModel.java

- Bug fix when request has been declined and another is made (`requests.size()` without status filter will make it > 1)
Closes #149

Fix multiple requests on same book by same user with different state

---

app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryViewModel.java

- Update Unlibrary's selected book even when page stays still
Closes #161

Update currentBook in Unlibrary through listener

---

app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java

- Display books as available regardless if the current user has already requested for it
Closes #122

Fix status in Exchange

---

app/build.gradle
app/src/main/java/com/example/unlibrary/util/PushNotificationService.java

**UNINSTALL THE APP AND REINSTALL TO GET NOTIFICATIONS TO WORKS**
- Set up a notification channel

Fix notification

---

app/src/main/java/com/example/unlibrary/library/LibraryBookDetailsFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryMapsFragment.java
app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java

- Refactor to listen to the Requests collection for the currently selected book 
- To Reproduce the bug:
- Accept a request on a book and select a handoff location. 
- Navigate back to Library and select any other book (I found the bug occurred when selecting a "Requested" book)
- Navigate to a previously accepted book and a toast notification will pop up.
- Note: I think Caleb also saw this bug just from accepting a book 
Closes #163

Fix: "Error getting handoff location" Toast 

---

app/src/main/java/com/example/unlibrary/library/LibraryViewModel.java

Fix: null pointer exception when setting up handoff listener

---

app/src/main/java/com/example/unlibrary/exchange/ExchangeRepository.java
app/src/main/java/com/example/unlibrary/library/LibraryRepository.java
app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
app/src/main/java/com/example/unlibrary/unlibrary/UnlibraryRepository.java
app/src/test/java/com/example/unlibrary/library/LibraryRepositoryTest.java

- Since LibraryRepository now waits for authStateChange, we need to mock it in the tests as well
Closes #158

Fix library repository unit test

---

README.md

Updated name on readme

---

.github/workflows/main.yml
app/src/main/java/com/example/unlibrary/profile/ProfileRepository.java
app/src/test/java/com/example/unlibrary/library/LibraryRepositoryTest.java
app/src/test/java/com/example/unlibrary/profile/ProfileRepositoryTest.java

- Added unit test for profile repository
- I could not mock the firebase auth properly so I couldn't test updated the user information, if anyone has any suggestions please let me know. The main issue is mocking the `Task<Void>` that `FiremAuth.getCurrentUser().updateEmail(...)` returns and setting the `.addOnCompleteListener` 
Closes #53 
Closes #77

Profile Repository Unit Test
